name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: abhishekverma2656
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Publish Snake to output branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git fetch origin
          git checkout --orphan output

          git rm -rf . 2>/dev/null || true

          cp dist/github-contribution-grid-snake.svg .
          cp dist/github-contribution-grid-snake-dark.svg .

          git add .
          git commit -m "Generate snake animation"
          git push -f origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
